baseURL = "http://localhost:1313/"
title = "The Egg-celent Cafe"
theme = "restaurant-hugo"
languageCode = "en-us"

[params]
  site_name = "The Egg-celent Cafe"
  logo = "images/logo.png"
  subtitle = "The Perfect Place to Start Your Day"
  footer_text = "© 2025 The Egg-celent Cafe. All rights reserved."
  phone = "+1 (555) 123-4567"
  email = "contact@eggcelentcafe.com"
  address = "123 Breakfast Lane, Sunnyside City, USA"
  hero_image = "images/slider/hero.jpg"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Menu"
  url = "/menu"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

  [[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 4

